#!/bin/sh
#Script to generate all the data 
#need to be admin
make clean 
make
#-------------------OTHER IO LIGHT --------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_OTHER_Light_IO
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_OTHER_Light_IO -a  ./test-sched SCHED_OTHER LIGHT IO
done
echo "1 done"
#---------------OTHER CPU LIGHT -----------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_OTHER_Light_CPU
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_OTHER_Light_CPU -a  ./test-sched SCHED_OTHER LIGHT CPU
done
echo "2 done"
#--------------OTHER HYBRID LIGHT ---------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_OTHER_Light_HYBRID
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_OTHER_Light_HYBRID -a  ./test-sched SCHED_OTHER LIGHT HYBRID
done
echo "3 done"
#-------------------OTHER IO MEDIUM --------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_OTHER_Medium_IO
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_OTHER_Medium_IO -a  ./test-sched SCHED_OTHER MEDIUM IO
done
echo "4 done"
#---------------OTHER CPU MEDIUM -----------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_OTHER_Medium_CPU
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_OTHER_Medium_CPU -a  ./test-sched SCHED_OTHER MEDIUM CPU
done
echo "5 done"
#--------------OTHER HYBRID MEDIUM ---------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_OTHER_Medium_HYBRID
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_OTHER_Medium_HYBRID -a  ./test-sched SCHED_OTHER MEDIUM HYBRID
done
echo "6 done"
#-------------------OTHER IO HEAVY --------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_OTHER_Heavy_IO
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_OTHER_Heavy_IO -a  ./test-sched SCHED_OTHER HEAVY IO
done
echo "7 done"
#---------------OTHER CPU HEAVY -----------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_OTHER_Heavy_CPU
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_OTHER_Heavy_CPU -a  ./test-sched SCHED_OTHER HEAVY CPU
done
echo "8 done"
#--------------OTHER HYBRID HEAVY ---------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_OTHER_Heavy_HYBRID
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_OTHER_Heavy_HYBRID -a  ./test-sched SCHED_OTHER HEAVY HYBRID
done
echo "9 done"
#-------------------RR IO LIGHT --------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_RR_Light_IO
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_RR_Light_IO -a  ./test-sched SCHED_RR LIGHT IO
done
echo "10 done"
#---------------RR CPU LIGHT -----------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_RR_Light_CPU
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_RR_Light_CPU -a  ./test-sched SCHED_RR LIGHT CPU
done
echo "11 done"
#--------------RR HYBRID LIGHT ---------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_RR_Light_HYBRID
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_RR_Light_HYBRID -a  ./test-sched SCHED_RR LIGHT HYBRID
done
echo "12 done"
#-------------------RR IO MEDIUM --------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_RR_Medium_IO
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_RR_Medium_IO -a  ./test-sched SCHED_RR MEDIUM IO
done
echo "13 done"
#---------------RR CPU MEDIUM -----------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_RR_Medium_CPU
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_RR_Medium_CPU -a  ./test-sched SCHED_RR MEDIUM CPU
done
echo "14 done"
#--------------RR HYBRID MEDIUM ---------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_RR_Medium_HYBRID
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_RR_Medium_HYBRID -a  ./test-sched SCHED_RR MEDIUM HYBRID
done
echo "15 done"
#-------------------RR IO HEAVY --------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_RR_Heavy_IO
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_RR_Heavy_IO -a  ./test-sched SCHED_RR HEAVY IO
done
echo "16 done"
#---------------RR CPU HEAVY -----------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_RR_Heavy_CPU
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_RR_Heavy_CPU -a  ./test-sched SCHED_RR HEAVY CPU
done
echo "17 done"
#--------------RR HYBRID HEAVY ---------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_RR_Heavy_HYBRID
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_RR_Heavy_HYBRID -a  ./test-sched SCHED_RR HEAVY HYBRID
done
echo "18 done"
#-------------------FIFO IO LIGHT --------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_FIFO_Light_IO
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_FIFO_Light_IO -a  ./test-sched SCHED_FIFO LIGHT IO
done
echo "19 done"
#---------------FIFO CPU LIGHT -----------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_FIFO_Light_CPU
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_FIFO_Light_CPU -a  ./test-sched SCHED_FIFO LIGHT CPU
done
echo "20 done"
#--------------FIFO HYBRID LIGHT ---------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_FIFO_Light_HYBRID
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_FIFO_Light_HYBRID -a  ./test-sched SCHED_FIFO LIGHT HYBRID
done
echo "21 done"
#-------------------FIFO IO MEDIUM --------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_FIFO_Medium_IO
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_FIFO_Medium_IO -a  ./test-sched SCHED_FIFO MEDIUM IO
done
echo "22 done"
#---------------FIFO CPU MEDIUM -----------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_FIFO_Medium_CPU
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_FIFO_Medium_CPU -a  ./test-sched SCHED_FIFO MEDIUM CPU
done
echo "23 done"
#--------------FIFO HYBRID MEDIUM ---------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_FIFO_Medium_HYBRID
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_FIFO_Medium_HYBRID -a  ./test-sched SCHED_FIFO MEDIUM HYBRID
done
echo "24 done"
#-------------------FIFO IO HEAVY --------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_FIFO_Heavy_IO
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_FIFO_Heavy_IO -a  ./test-sched SCHED_FIFO HEAVY IO
done
echo "25 done"
#---------------FIFO CPU HEAVY -----------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_FIFO_Heavy_CPU
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_FIFO_Heavy_CPU -a  ./test-sched SCHED_FIFO HEAVY CPU
done
echo "26 done"
#--------------FIFO HYBRID HEAVY ---------------------------------

echo "%Real Time (s), Time spent in Kernel Mode (s), Time spent in user mode, Percentage of the CPU gotten, Involuntarily Contex switches, Voluntarily context switchs " > data_FIFO_Heavy_HYBRID
for i in 1 2 3
do
/usr/bin/time --format="%e,%S,%U,%P,%c,%w" -o data_FIFO_Heavy_HYBRID -a  ./test-sched SCHED_FIFO HEAVY HYBRID
done
echo "27 done"
#------------------------DATA MOVING--------------------------
mv data_* bfs

